### PR TITLE
66 view service part delete service part

### PR DESCRIPTION
**Pull request by 9fc70c892**
only thing is that both is not tested yet

### CODE REVIEW

**Comment by 9fc70c892** [comment]
In view of #71, do not merge yet

**Comment by 9fc70c892** [comment]
see #76

**Comment by 9fc70c892** [comment]
> In view of #71, do not merge yet

Miiiight be fixed.

**Comment by 9fc70c892** [comment]
Might conflict with #78

**Review by kimberlybp — APPROVED** [review]

**Review by junlee1991 — APPROVED** [review]

**Pull request merged**
