### PR TITLE
Branch view + Branch Delete

### PR DESCRIPTION
**Pull request by 9fc70c892**
NGL I half forgot what I did.

Primarily: 
viewappointment
viewservice
viewvehicle
viewpart

waiting on #30 for on partmap for viewpartcommand:31

### CODE REVIEW

**Comment by 9fc70c892** [comment]
fixing javadocs before removing draft label

**Comment by 9fc70c892** [comment]
#55

**Comment by 9fc70c892** [comment]
Expected #61 to alter behavior of Parts, PR will revert to DRAFT to amend for it

**Comment by 9fc70c892** [comment]
#60 

Exception is deleteservice, due to not present in [userguide ](https://github.com/AY2223S2-CS2103-W17-4/tp/blob/master/docs/UserGuide.md)as of implementation

**Comment by 9fc70c892** [comment]
Technically "not ready" until GUI is up

**Review by kimberlybp — APPROVED** [review]

**Pull request merged**
